version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Singapore
    open-pull-requests-limit: 10
    reviewers:
      - "Accredify/DevSecOps"
      - "Accredifysg/saas-tech-leads"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Singapore
    open-pull-requests-limit: 10
    reviewers:
      - "Accredify/DevSecOps"
