name: Generate Coverage Badge
on:
  workflow_call:
    inputs:
      coverage:
        type: string
        required: true
jobs:
  badge:
    name: Generate Coverage Badge
    runs-on: ubuntu-20.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      # Checkout Code (current branch)
      - name: Checkout
        uses: actions/checkout@v2

      # Use the output from the `coverage` step
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1.2.4
        id: badge
        with:
          label: 'Test coverage'
          status: ${{ inputs.coverage }}
          color: ${{
            inputs.coverage > 90 && 'green'              ||
            inputs.coverage > 80 && 'yellow,green'       ||
            inputs.coverage > 70 && 'yellow'             ||
            inputs.coverage > 60 && 'orange,yellow'      ||
            inputs.coverage > 50 && 'orange'             ||
            inputs.coverage > 40 && 'red,orange'         ||
            inputs.coverage > 30 && 'red,red,orange'     ||
            inputs.coverage > 20 && 'red,red,red,orange' ||
            'red' }}
          path: "coverage/badge.svg"

      # Upload badge as artifact
      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: badge
          path: "coverage/badge.svg"
          if-no-files-found: error

      # Commit badge
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: update coverage & badge'
          commit_options: '--no-verify'
