name: CI
on:
  workflow_call:
    outputs:
      coverage:
        description: "Code coverage value"
        value: ${{ jobs.ci.outputs.coverage }}
    secrets:
      SONAR_TOKEN:
        required: false

jobs:
  ci:
    name: Feature & Unit Tests
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}

    steps:
      # Checkout Code (current branch)
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Install PHP
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.3"
          extensions: mbstring, mysql
          coverage: xdebug

      # Get composer cache
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      # Cache composer dependencies
      - name: Cache composer dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Install composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # Generate code coverage
      - name: Generate code coverage
        run: ./vendor/bin/phpunit --coverage-clover=coverage/clover.xml

      # Check test coverage
      - name: Check test coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@2543c79a701f179bd63aa14c16c6938c509b2cec # v1
        id: coverage
        with:
          percentage: "80"
          filename: "coverage/clover.xml"

      # Run Pint
      - name: Run Pint
        run: vendor/bin/pint

      # Commit everything
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "fix: code-style"
          commit_options: "--no-verify"

      # Upload Coverage Report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: coverage/clover.xml

      # SonarCloud Scan
      - name: SonarCloud Scan
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/master')
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}