name: CI
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  badge:
    needs: ci
    name: Generate Coverage Badge
    uses: ./.github/workflows/badge.yml
    with:
      coverage: ${{ needs.ci.outputs.coverage }}
