name: Merge to Master Branch
on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}